name: RDP 2026
on: workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: RustDesk
        run: |
          Invoke-WebRequest -Uri https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe -OutFile rustdesk.exe
          .\rustdesk.exe --install-service
          Start-Sleep -Seconds 10
          $id = & "C:\Program Files\RustDesk\rustdesk.exe" --get-id
          Write-Host "====== ID RUSTDESK: $id ======"
          Write-Host "====== MOT DE PASSE: Mets un mdp dans RustDesk Viewer ======"
          for($i=0; $i -lt 360; $i++){ Write-Host "ON $i min - ID $id"; Start-Sleep 60 }
